version: "3.7"

services: 
  urlshortner:
    #build: . 
    #build: https://github.com/ahd99/urlshortner.git
    build:
      context: ./.. # set context to project root
      dockerfile: ./devops/Dockerfile  # Dockerfile path relative to context
    image: urlshortner:test
    ports: 
      - "8081:8081"   # url shortner rest api
      - "8091:8091"   # monitoring grpc api
    networks: 
      - urlshortner-network
    depends_on: 
      - mongo

  mongo:
    image: mongo
    command: --bind_ip 0.0.0.0
    # restart: always
    ports: 
      - "27018:27017"
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes: 
      - ~/workspace/data/mongo-docker-volume:/data/db
    networks: 
      - urlshortner-network
    

  prometheus:
    image: prom/prometheus
    command: --config.file=/etc/prometheus/prometheus.yml 
    ports: 
      - "9090:9090"
    networks: 
      - urlshortner-network
    volumes: 
      - ~/workspace/urlshortner/scripts/prometheus-config.yml:/etc/prometheus/prometheus.yml
      #- ~/workspace/data/prometheus-docker-volume:/prometheus

  grafana:
    image: grafana/grafana
    ports: 
      - "3000:3000"
    networks: 
      - urlshortner-network
    

networks: 
  urlshortner-network : {}

