apiVersion: v1
kind: Pod
metadata:
  name: urls-pod  # pod name
  labels:
    app: urls-app
spec:
  containers:
  - name: urls-container  # container name
    image: aaa59/urlshortner:nomongo  # image address on docker hub
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - name: urls-port-1
        containerPort: 8081   # without this line, yet port forward to 8081 in pod works.
