// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MonitoringClient is the client API for Monitoring service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MonitoringClient interface {
	Statistics(ctx context.Context, in *StatReq, opts ...grpc.CallOption) (Monitoring_StatisticsClient, error)
	TranList(ctx context.Context, in *TranListReq, opts ...grpc.CallOption) (Monitoring_TranListClient, error)
}

type monitoringClient struct {
	cc grpc.ClientConnInterface
}

func NewMonitoringClient(cc grpc.ClientConnInterface) MonitoringClient {
	return &monitoringClient{cc}
}

func (c *monitoringClient) Statistics(ctx context.Context, in *StatReq, opts ...grpc.CallOption) (Monitoring_StatisticsClient, error) {
	stream, err := c.cc.NewStream(ctx, &Monitoring_ServiceDesc.Streams[0], "/monitoring.Monitoring/Statistics", opts...)
	if err != nil {
		return nil, err
	}
	x := &monitoringStatisticsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Monitoring_StatisticsClient interface {
	Recv() (*StatResp, error)
	grpc.ClientStream
}

type monitoringStatisticsClient struct {
	grpc.ClientStream
}

func (x *monitoringStatisticsClient) Recv() (*StatResp, error) {
	m := new(StatResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *monitoringClient) TranList(ctx context.Context, in *TranListReq, opts ...grpc.CallOption) (Monitoring_TranListClient, error) {
	stream, err := c.cc.NewStream(ctx, &Monitoring_ServiceDesc.Streams[1], "/monitoring.Monitoring/TranList", opts...)
	if err != nil {
		return nil, err
	}
	x := &monitoringTranListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Monitoring_TranListClient interface {
	Recv() (*TranListResp, error)
	grpc.ClientStream
}

type monitoringTranListClient struct {
	grpc.ClientStream
}

func (x *monitoringTranListClient) Recv() (*TranListResp, error) {
	m := new(TranListResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MonitoringServer is the server API for Monitoring service.
// All implementations must embed UnimplementedMonitoringServer
// for forward compatibility
type MonitoringServer interface {
	Statistics(*StatReq, Monitoring_StatisticsServer) error
	TranList(*TranListReq, Monitoring_TranListServer) error
	mustEmbedUnimplementedMonitoringServer()
}

// UnimplementedMonitoringServer must be embedded to have forward compatible implementations.
type UnimplementedMonitoringServer struct {
}

func (UnimplementedMonitoringServer) Statistics(*StatReq, Monitoring_StatisticsServer) error {
	return status.Errorf(codes.Unimplemented, "method Statistics not implemented")
}
func (UnimplementedMonitoringServer) TranList(*TranListReq, Monitoring_TranListServer) error {
	return status.Errorf(codes.Unimplemented, "method TranList not implemented")
}
func (UnimplementedMonitoringServer) mustEmbedUnimplementedMonitoringServer() {}

// UnsafeMonitoringServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MonitoringServer will
// result in compilation errors.
type UnsafeMonitoringServer interface {
	mustEmbedUnimplementedMonitoringServer()
}

func RegisterMonitoringServer(s grpc.ServiceRegistrar, srv MonitoringServer) {
	s.RegisterService(&Monitoring_ServiceDesc, srv)
}

func _Monitoring_Statistics_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StatReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MonitoringServer).Statistics(m, &monitoringStatisticsServer{stream})
}

type Monitoring_StatisticsServer interface {
	Send(*StatResp) error
	grpc.ServerStream
}

type monitoringStatisticsServer struct {
	grpc.ServerStream
}

func (x *monitoringStatisticsServer) Send(m *StatResp) error {
	return x.ServerStream.SendMsg(m)
}

func _Monitoring_TranList_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TranListReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MonitoringServer).TranList(m, &monitoringTranListServer{stream})
}

type Monitoring_TranListServer interface {
	Send(*TranListResp) error
	grpc.ServerStream
}

type monitoringTranListServer struct {
	grpc.ServerStream
}

func (x *monitoringTranListServer) Send(m *TranListResp) error {
	return x.ServerStream.SendMsg(m)
}

// Monitoring_ServiceDesc is the grpc.ServiceDesc for Monitoring service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Monitoring_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "monitoring.Monitoring",
	HandlerType: (*MonitoringServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Statistics",
			Handler:       _Monitoring_Statistics_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "TranList",
			Handler:       _Monitoring_TranList_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/monitoring/proto/monitoring.proto",
}
